const heroSlides=[{title:"Samurai Sunset",desc:"AMOLED dark wallpaper for your phone screen.",cat:"Samurai",img:"https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=80"},{title:"Cyber City",desc:"Neon cyberpunk vibes with premium colors.",cat:"Cyberpunk",img:"https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=80"},{title:"Red Planet",desc:"Deep space AMOLED wallpaper collection.",cat:"Space",img:"https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1200&q=80"}];
const categories=[["AMOLED","★","2.4K"],["Anime","👻","3.7K"],["Cars","🚗","2.1K"],["Nature","🌲","1.8K"],["Gaming","🎮","1.3K"],["Minimal","✦","890"]];
const wallpapers=[{title:"Car",cat:"Cars",views:"2.5K",likes:"256",downs:"1.1K",img:"https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80"},{title:"Anime",cat:"Anime",views:"3.1K",likes:"362",downs:"1.7K",img:"https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80"},{title:"Dark Wall",cat:"AMOLED",views:"1.8K",likes:"198",downs:"893",img:"https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80"},{title:"Supercar",cat:"Cars",views:"2.2K",likes:"275",downs:"1.3K",img:"https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=600&q=80"},{title:"Purple Space",cat:"Space",views:"4.2K",likes:"520",downs:"2.4K",img:"https://images.unsplash.com/photo-1447433819943-74a20887a81e?auto=format&fit=crop&w=600&q=80"},{title:"Nature Lake",cat:"Nature",views:"3.8K",likes:"410",downs:"1.9K",img:"https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=600&q=80"},{title:"Gaming Neon",cat:"Gaming",views:"2.9K",likes:"301",downs:"1.5K",img:"https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80"},{title:"AMOLED Stars",cat:"AMOLED",views:"5.1K",likes:"693",downs:"3.1K",img:"https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?auto=format&fit=crop&w=600&q=80"}];
const notes=[["New wallpaper added","Cyber City","2m ago",wallpapers[6].img],["Trending now","Purple Space","15m ago",wallpapers[4].img],["Download complete","Samurai Sunset","30m ago",wallpapers[0].img]];
let heroIndex=0,currentWallpaper=wallpapers[0],favorites=JSON.parse(localStorage.getItem("wfh_favorites")||"[]"),downloads=JSON.parse(localStorage.getItem("wfh_downloads")||"[]");const $=id=>document.getElementById(id);
function init(){renderHeroDots();setHero(0);renderCategories();renderCards("trendingGrid",wallpapers.slice(0,4));renderCards("latestGrid",wallpapers.slice(4,8));renderCards("resultsGrid",wallpapers);renderCards("relatedGrid",wallpapers.slice(1,6));renderNotifications();renderFavorites();renderDownloads();updateCounts();setInterval(()=>setHero((heroIndex+1)%heroSlides.length),5000)}
function renderHeroDots(){$("heroDots").innerHTML=heroSlides.map((_,i)=>`<button class="${i===0?'active':''}" onclick="setHero(${i})"></button>`).join("")}
function setHero(i){heroIndex=i;const h=heroSlides[i];$("hero").style.backgroundImage=`url('${h.img}')`;$("heroTitle").textContent=h.title;$("heroDesc").textContent=h.desc;[...$("heroDots").children].forEach((d,x)=>d.classList.toggle("active",x===i))}
function renderCategories(){$("categoriesRow").innerHTML=categories.map(c=>`<div class="cat-card" onclick="quickSearch('${c[0]}')"><div class="icon">${c[1]}</div><b>${c[0]}</b><small>👁 ${c[2]}</small></div>`).join("")}
function cardHTML(w){const liked=favorites.some(f=>f.title===w.title);return `<article class="wall-card" onclick='openDetails(${JSON.stringify(w)})'><div class="wall-img" style="background-image:url('${w.img}')"><span class="badge-left">${w.cat}</span><div class="badge-right"><span class="badge-new">NEW</span><span class="badge-cdn">CDN</span></div></div><div class="wall-info"><h3>${w.title}</h3><div class="wall-stats"><span>👁 ${w.views}</span><span>♡ ${w.likes}</span><span>⇩ ${w.downs}</span></div><div class="wall-actions"><button onclick='event.stopPropagation();toggleFav(${JSON.stringify(w)})'>${liked?'♥':'♡'}</button><button onclick='event.stopPropagation();downloadWallpaper(${JSON.stringify(w)})'>⇩ Download</button></div></div></article>`}
function renderCards(id,list){$(id).innerHTML=list.map(cardHTML).join("")}
function openDetails(w){currentWallpaper=w;$("detailHero").style.backgroundImage=`url('${w.img}')`;$("detailTitle").textContent=w.title;$("detailCat").textContent=w.cat+" Collection";$("detailViews").textContent=w.views;$("detailLikes").textContent=w.likes;$("detailDowns").textContent=w.downs;openPage("detailsPage")}
function toggleFav(w){const i=favorites.findIndex(f=>f.title===w.title);if(i>=0){favorites.splice(i,1);toast("Removed from favorites")}else{favorites.push(w);toast("Added to favorites")}localStorage.setItem("wfh_favorites",JSON.stringify(favorites));renderCards("trendingGrid",wallpapers.slice(0,4));renderCards("latestGrid",wallpapers.slice(4,8));renderCards("resultsGrid",wallpapers);renderFavorites();updateCounts()}
function renderFavorites(){$("favoritesGrid").innerHTML=favorites.length?favorites.map(cardHTML).join(""):`<div class="empty">No favorite wallpapers yet</div>`}
function clearFavorites(){favorites=[];localStorage.setItem("wfh_favorites","[]");renderFavorites();updateCounts();toast("Favorites cleared")}
function downloadWallpaper(w){downloads.unshift(w);localStorage.setItem("wfh_downloads",JSON.stringify(downloads.slice(0,20)));renderDownloads();updateCounts();const a=document.createElement("a");a.href=w.img;a.target="_blank";a.download=w.title+".jpg";a.click();toast("Download started")}
function downloadHero(){const h=heroSlides[heroIndex];downloadWallpaper({title:h.title,cat:h.cat,views:"4.9K",likes:"700",downs:"3.3K",img:h.img})}
function renderDownloads(){$("downloadsList").innerHTML=downloads.length?downloads.map(d=>`<div class="note"><img src="${d.img}"><div><h3>${d.title}</h3><p>Downloaded wallpaper</p></div><small>now</small></div>`).join(""):`<div class="empty">No downloads yet</div>`}
function renderNotifications(){$("notificationsList").innerHTML=notes.map(n=>`<div class="note"><img src="${n[3]}"><div><h3>${n[0]}</h3><p>${n[1]}</p></div><small>${n[2]}</small></div>`).join("")}
function searchWallpapers(){const q=$("searchInput").value.toLowerCase();$("resultTitle").textContent=q?`Results for "${q}"`:"Results";const res=q?wallpapers.filter(w=>(w.title+w.cat).toLowerCase().includes(q)):wallpapers;renderCards("resultsGrid",res.length?res:wallpapers)}
function quickSearch(q){openPage("searchPage");$("searchInput").value=q;searchWallpapers()}
function openPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(id).classList.add("active");window.scrollTo(0,0);toggleMenu(false);setBottom(id)}
function goHome(){openPage("homePage")}
function setBottom(id){document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.remove("active"));const map={homePage:0,favoritesPage:2,notificationsPage:3};document.querySelectorAll(".bottom-nav button")[map[id]??0].classList.add("active")}
function scrollHome(id){goHome();setTimeout(()=>$(`${id}`).scrollIntoView({behavior:"smooth",block:"start"}),120)}
function toggleMenu(show){$("sidebar").classList.toggle("open",show);$("overlay").classList.toggle("show",show)}
function toggleTheme(){document.body.classList.toggle("light");toast(document.body.classList.contains("light")?"Light mode":"Dark mode")}
function changeLanguage(){const langs=["English","العربية","Français","Español"];const cur=$("langText").textContent;const next=langs[(langs.indexOf(cur)+1)%langs.length];$("langText").textContent=next;$("settingsLang").textContent=next;toast("Language: "+next)}
function shareApp(){if(navigator.share){navigator.share({title:"WallFlixHub",url:location.href})}else{navigator.clipboard?.writeText(location.href);toast("Link copied")}}
function shareWallpaper(w){if(navigator.share){navigator.share({title:w.title,url:w.img})}else{navigator.clipboard?.writeText(w.img);toast("Wallpaper link copied")}}
function updateCounts(){$("favMenuCount").textContent=favorites.length;$("favCount").textContent=favorites.length;$("downCount").textContent=downloads.length}
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1600)}
init();
